# AAJ hoga pandas khatam
:🫡

In [1]:
# pandas 01

In [3]:
import pandas as pd
marks = pd.Series([80,74,90,64])
print(marks)

0    80
1    74
2    90
3    64
dtype: int64

In [6]:
df = pd.DataFrame({
    "name":["rajmani", "ritik","bhadvaj"],
    "roll": [20,21,22],
    "marks":[80,75,60]
},index = ["a", "b ", "c"])
print(df)

       name  roll  marks
a   rajmani    20     80
b     ritik    21     75
c   bhadvaj    22     60

In [7]:
db = pd.read_csv("/content/phishing_training_data.csv")
print (db)

      url_count  ip_url_count  suspicious_tld_count  long_url_count  \
0             0             0                     2               1
1             3             0                     0               0
2             1             1                     2               1
3             0             0                     0               0
4             1             0                     0               0
...         ...           ...                   ...             ...
9995          3             1                     1               1
9996          1             0                     0               0
9997          0             0                     0               0
9998          1             1                     2               1
9999          1             0                     0               0

      urgent_count  credential_count  threat_count  reply_to_mismatch  \
0                1                 1             1                  0
1                1                 1             4                  0
2                6                 6             0                  0
3                6                 1             0                  0
4                1                 1             0                  0
...            ...               ...           ...                ...
9995             5                 1             1                  1
9996             0                 0             0                  0
9997             0                 0             1                  0
9998             6                 2             0                  1
9999             0                 1             1                  0

      attachment_count  suspicious_attachment_count  text_length  \
0                    2                            2         1216
1                    2                            0         1566
2                    2                            0          965
3                    0                            0          194
4                    0                            0          570
...                ...                          ...          ...
9995                 0                            0          415
9996                 0                            0          431
9997                 0                            0          109
9998                 0                            0         1680
9999                 0                            0          702

      exclamation_count  phishing_percentage  label
0                     1                   81      1
1                     8                   75      1
2                     5                   53      1
3                     6                   35      0
4                     0                   12      0
...                 ...                  ...    ...
9995                  6                   75      1
9996                  1                    7      0
9997                  1                   15      0
9998                  7                   97      1
9999                  0                   16      0

[10000 rows x 14 columns]

In [8]:
# save dataFrame to csv

In [9]:
df.to_csv("data.csv", index= False)
# in this false denote that the index is hidden

In [10]:
dt = pd.read_csv("/content/data.csv")
print(dt)

      name  roll  marks
0  rajmani    20     80
1    ritik    21     75
2  bhadvaj    22     60

In [11]:
db.head()

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
0,0,0,2,1,1,1,1,0,2,2,1216,1,81,1
1,3,0,0,0,1,1,4,0,2,0,1566,8,75,1
2,1,1,2,1,6,6,0,0,2,0,965,5,53,1
3,0,0,0,0,6,1,0,0,0,0,194,6,35,0
4,1,0,0,0,1,1,0,0,0,0,570,0,12,0

In [12]:
db.tail()

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
9995,3,1,1,1,5,1,1,1,0,0,415,6,75,1
9996,1,0,0,0,0,0,0,0,0,0,431,1,7,0
9997,0,0,0,0,0,0,1,0,0,0,109,1,15,0
9998,1,1,2,1,6,2,0,1,0,0,1680,7,97,1
9999,1,0,0,0,0,1,1,0,0,0,702,0,16,0

In [13]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   roll    3 non-null      int64
 2   marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [14]:
print(db.shape)

(10000, 14)

In [15]:
print(db.columns)

Index(['url_count', 'ip_url_count', 'suspicious_tld_count', 'long_url_count',
       'urgent_count', 'credential_count', 'threat_count', 'reply_to_mismatch',
       'attachment_count', 'suspicious_attachment_count', 'text_length',
       'exclamation_count', 'phishing_percentage', 'label'],
      dtype='object')

In [16]:
print(db.dtypes)

url_count                      int64
ip_url_count                   int64
suspicious_tld_count           int64
long_url_count                 int64
urgent_count                   int64
credential_count               int64
threat_count                   int64
reply_to_mismatch              int64
attachment_count               int64
suspicious_attachment_count    int64
text_length                    int64
exclamation_count              int64
phishing_percentage            int64
label                          int64
dtype: object

In [18]:
db["text_length"]

0       1216
1       1566
2        965
3        194
4        570
        ...
9995     415
9996     431
9997     109
9998    1680
9999     702
Name: text_length, Length: 10000, dtype: int64

In [19]:
db[["text_length", "label"
]]

      text_length  label
0            1216      1
1            1566      1
2             965      1
3             194      0
4             570      0
...           ...    ...
9995          415      1
9996          431      0
9997          109      0
9998         1680      1
9999          702      0

[10000 rows x 2 columns]

In [20]:
df.iloc[:,0]

a     rajmani
b       ritik
c     bhadvaj
Name: name, dtype: object

In [21]:
db.iloc[:,2]

0       2
1       0
2       2
3       0
4       0
       ..
9995    1
9996    0
9997    0
9998    2
9999    0
Name: suspicious_tld_count, Length: 10000, dtype: int64

In [22]:
db.iloc[0,1]
# specific row and columns

np.int64(0)

In [24]:
db.iloc[0:3,1:3]

   ip_url_count  suspicious_tld_count
0             0                     2
1             0                     0
2             1                     2

In [25]:
# iloc refer to position , index number se selection

In [26]:
# loc ho gya labels/names ke basis paar

In [28]:

db.loc[0]

url_count                         0
ip_url_count                      0
suspicious_tld_count              2
long_url_count                    1
urgent_count                      1
credential_count                  1
threat_count                      1
reply_to_mismatch                 0
attachment_count                  2
suspicious_attachment_count       2
text_length                    1216
exclamation_count                 1
phishing_percentage              81
label                             1
Name: 0, dtype: int64

In [30]:
db.loc[:,"text_length"]

0       1216
1       1566
2        965
3        194
4        570
        ...
9995     415
9996     431
9997     109
9998    1680
9999     702
Name: text_length, Length: 10000, dtype: int64

In [31]:
db.loc[db["text_length"]>100 , ["url_count"]]

      url_count
0             0
1             3
2             1
3             0
4             1
...         ...
9995          3
9996          1
9997          0
9998          1
9999          1

[9991 rows x 1 columns]

In [32]:
df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Neha", "Priya"],
    "age": [20, 21, 19, 22],
    "marks": [80, 75, 90, 65]
})

In [33]:
df[df["marks"]>80]

   name  age  marks
2  Neha   19     90

In [34]:
df[(df["marks"]>80) | (df["age"] > 20)]

    name  age  marks
1  Rahul   21     75
2   Neha   19     90
3  Priya   22     65

In [35]:
df["passed"] = df["marks"]>=75

In [36]:
print(df)

    name  age  marks  passed
0   Amit   20     80    True
1  Rahul   21     75    True
2   Neha   19     90    True
3  Priya   22     65   False

In [37]:
df["bonus_marks"] = df["marks"] + 5

In [38]:
df

    name  age  marks  passed  bonus_marks
0   Amit   20     80    True           85
1  Rahul   21     75    True           80
2   Neha   19     90    True           95
3  Priya   22     65   False           70

In [39]:
#  remove columns

In [40]:
df.drop("bonus_marks" , axis = 1)

    name  age  marks  passed
0   Amit   20     80    True
1  Rahul   21     75    True
2   Neha   19     90    True
3  Priya   22     65   False

In [41]:
df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Neha"],
    "age": [20, None, 19],
    "marks": [80, 75, None]
})

In [42]:
df.isnull()

    name    age  marks
0  False  False  False
1  False   True  False
2  False  False   True

In [43]:
df.isnull().sum()

name     0
age      1
marks    1
dtype: int64

In [44]:
df.dropna()

   name   age  marks
0  Amit  20.0   80.0

In [45]:
df = pd.DataFrame({
    "name": ["Amit", "Rahul", "Neha"],
    "age": [20, None, 19],
    "marks": [80, 75, None]
})

In [46]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [48]:
df.sort_values("marks", ascending = False)

    name   age  marks
0   Amit  20.0   80.0
1  Rahul   NaN   75.0
2   Neha  19.0    NaN

In [49]:
df = pd.DataFrame({
    "department": ["CS", "CS", "IT", "IT", "CS"],
    "name": ["A", "B", "C", "D", "E"],
    "marks": [80, 90, 70, 85, 75]
})

In [50]:
df.groupby("department")["marks"].mean()

department
CS    81.666667
IT    77.500000
Name: marks, dtype: float64

In [51]:
df.groupby("department")["marks"].sum()

department
CS    245
IT    155
Name: marks, dtype: int64

In [52]:
df.groupby("department")["marks"].agg(
    ["mean", "sum", "min", "max"]
)

                 mean  sum  min  max
department
CS          81.666667  245   75   90
IT          77.500000  155   70   85

In [53]:
df1 = pd.DataFrame({
    "name": ["A", "B"],
    "marks": [80, 90]
})

df2 = pd.DataFrame({
    "name": ["C", "D"],
    "marks": [70, 85]
})

result = pd.concat([df1, df2])

print(result)

  name  marks
0    A     80
1    B     90
0    C     70
1    D     85

In [54]:
students = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["A", "B", "C"]
})

marks = pd.DataFrame({
    "id": [1, 2, 3],
    "marks": [80, 90, 75]
})

result = pd.merge(students, marks, on="id")

print(result)

   id name  marks
0   1    A     80
1   2    B     90
2   3    C     75

In [55]:
# kisi function ko columns ke har  value parr apply karna
df["marks"] = df["marks"].apply(lambda x: x + 5)

In [56]:
df

  department name  marks
0         CS    A     85
1         CS    B     95
2         IT    C     75
3         IT    D     90
4         CS    E     80

In [57]:
def grade(marks):
    if marks >= 80:
        return "A"
    elif marks >= 60:
        return "B"
    else:
        return "C"

df["grade"] = df["marks"].apply(grade)

In [58]:
df

  department name  marks grade
0         CS    A     85     A
1         CS    B     95     A
2         IT    C     75     B
3         IT    D     90     A
4         CS    E     80     A

In [59]:
df = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "gender": ["Male", "Female", "Male", "Female"]
})

In [62]:
pd.get_dummies(df["gender"])

   Female   Male
0   False   True
1    True  False
2   False   True
3    True  False

In [63]:
df

  name  gender
0    A    Male
1    B  Female
2    C    Male
3    D  Female

In [64]:
df = pd.DataFrame({
    "age": [20, 21, 22],
    "marks": [80, 90, 75]
})

array = df.to_numpy()

print(array)

[[20 80]
 [21 90]
 [22 75]]

In [65]:
import numpy as np

array = np.array([
    [20, 80],
    [21, 90],
    [22, 75]
])

df = pd.DataFrame(
    array,
    columns=["age", "marks"]
)

print(df)

   age  marks
0   20     80
1   21     90
2   22     75