In [ ]:
import numpy as np

In [ ]:
# panda work only on 1d

In [ ]:
import pandas as pd

In [ ]:
labels = ['a', 'b ','c']
my_list = [10,20,30]

In [ ]:
import numpy as np
arr = np.array([10,20,30])

In [ ]:
d = {1:10, 2:20, 3:30}

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
# in this upper bar the left parts is called the label (index), while the right side the normal list that is arrange in vertical order

In [ ]:
# custom label

In [ ]:
pd.Series(my_list,index=labels)

a     10
b     20
c     30
dtype: int64

In [ ]:
#  in this if you want to change the defualt index value into your known value then we can do use the feature index = labels

In [ ]:
#  in this pd.series(name of list, index name )

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
# array and series work similaiar but one caution is that array never become 2d

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
# in this if we send the dictionary then we got both key as label and value as data

In [ ]:
# dataframe =  collection of  series

In [ ]:
# create a datafram

In [ ]:
data ={
    'Name': ['john', 'Anna', 'Peter', 'Linda'],
    'Age' : [28, 24 , 35 , 42 ] ,
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary':[65000, 70000, 85000,0]
}
label = ['a', 'b', 'c', 'd']

In [ ]:
df = pd.DataFrame(data,index =label )

    Name  Age      City  Salary
a   john   28  New York   65000
b   Anna   24     Paris   70000
c  Peter   35    Berlin   85000
d  Linda   42    London   85000

In [ ]:
# using this we can create a data frame in panda using the pd.Dataframe(data, index) in which each key-> value are arrange as column wise and or we can say it is inform of collection of series

In [ ]:
# But the import part is that if you define 4 people then there must be a data for four people in all series if we miss the data in any series then we got error

In [ ]:
# same as for the list
import pandas as pd

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 35, 'Berlin', 85000],
    ['Linda', 42, 'London', 0]
]

In [ ]:
df = pd.DataFrame(data_list)
print(df)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  35    Berlin  85000
3  Linda  42    London      0

In [ ]:
# now in this list only the label is give but no the key are in this but the nameheader in the place of 01234

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 35, 'Berlin', 85000],
    ['Linda', 42, 'London', 0]
]

In [ ]:
df2 = pd.DataFrame(data_list)
df2
df3 = pd.DataFrame(data_list,columns=["Name","Age", "City", "Salary"])
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   35    Berlin   85000
3  Linda   42    London       0

In [ ]:
# in this using the columns we get the header of the table or collection of the series

In [ ]:
# second Topic
# selection and indexing of columns

In [ ]:
df3['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [ ]:
# using this df3[name of the series or we say the header of series]

In [ ]:
df3['Age']

0    28
1    34
2    35
3    42
Name: Age, dtype: int64

In [ ]:
# for selection two series or say to be 2 columns

In [ ]:
df3[['Name', 'Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   35
3  Linda   42

In [ ]:
# creating a column or append a column

In [ ]:
df3["Designation"]=['doctor', 'Engineer', 'doctor', 'surgion']

In [ ]:
df3

    Name  Age      City  Salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   35    Berlin   85000      doctor
3  Linda   42    London       0     surgion

In [ ]:
# in this if we again print the df3 we get the same table with Designation so for deleting the series permentatly we use 'inplace = True'
df3.drop('Age', axis=1 , inplace=True)

In [ ]:
# Remove a column  df3.drop('seriesName', axis = 1 '1 refer to Y axis and 0 refer to x axis by default)
# df3.drop('Designation',axis=1)

In [ ]:
df3

    Name      City  Salary Designation
0   John  New York   65000      doctor
1   Anna     Paris   70000    Engineer
2  Peter    Berlin   85000      doctor
3  Linda    London       0     surgion

In [ ]:
# for multiple remove
df3.drop(["City", "Salary"],axis = 1)

    Name Designation
0   John      doctor
1   Anna    Engineer
2  Peter      doctor
3  Linda     surgion

In [ ]:
df3.drop(0,axis = 0)
# means delete the rows of label 0

    Name    City  Salary Designation
1   Anna   Paris   70000    Engineer
2  Peter  Berlin   85000      doctor
3  Linda  London       0     surgion

In [ ]:
# Selecting a rows

In [ ]:
df3.loc[0]
# give location of the  rows

Name               John
City           New York
Salary            65000
Designation      doctor
Name: 0, dtype: object

In [ ]:
df.iloc[0]
# index location

0        John
1          28
2    New York
3       65000
Name: 0, dtype: object

In [ ]:
# Selection subset of rows and column

In [ ]:
df3.loc[[0,3]][["City", "Salary"]]
# in this the structre for selection the rows and column is simple
# df3.loc[[selecting 1 rows , selection 2 rows]]  [['selection1column, selection2columns]]

       City  Salary
0  New York   65000
3    London       0

    Name      City  Salary Designation
0   John  New York   65000      doctor
1   Anna     Paris   70000    Engineer
2  Peter    Berlin   85000      doctor
3  Linda    London       0     surgion

In [ ]:
df3.loc[[2,3]][['Name','City']]

    Name    City
2  Peter  Berlin
3  Linda  London

In [ ]:
# Conditional section

In [ ]:
df3

    Name      City  Salary Designation
0   John  New York   65000      doctor
1   Anna     Paris   70000    Engineer
2  Peter    Berlin   85000      doctor
3  Linda    London       0     surgion

In [ ]:
# I only want to see whose salary is greater than 65000

In [ ]:
df3[df3["Salary"]>65000]

    Name    City  Salary Designation
1   Anna   Paris   70000    Engineer
2  Peter  Berlin   85000      doctor

In [ ]:
# i only want people whose salary is greater than 65000 and  designatin is doctor

In [ ]:
df3[(df3["Salary"]>65000) & (df3["Designation"]=="doctor")]

    Name    City  Salary Designation
2  Peter  Berlin   85000      doctor

In [ ]:
# Missing data

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
data = {
    'A': [1,2,np.nan, 4,5],
    'B':[np.nan, 2,3,4,5],
    'C':[1,2,3,np.nan, np.nan],
    'D':[1,np.nan, np.nan, np.nan, 5]
}

In [ ]:
df = pd.DataFrame(data )

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()
# null value exist in each column

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
# Remove the null value  work on basis on row

In [ ]:
#df.dropna()
# if any null value exist in row then deleted

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
# df.dropna(thresh = 3)
# means delete the row where the not null value is less than 3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
# filling the missing the missing data

In [ ]:
df.fillna(0)
# means the Nan value are replace with 0

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [ ]:
values={'A': 101 , 'B': 1111, 'C': 224, 'D': 385}

In [ ]:
df.fillna(values)
# column wise fill

       A       B      C      D
0    1.0  1111.0    1.0    1.0
1    2.0     2.0    2.0  385.0
2  101.0     3.0    3.0  385.0
3    4.0     4.0  224.0  385.0
4    5.0     5.0  224.0    5.0

In [ ]:
# fill the mean
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [ ]:
# Merging joining and concatination

In [ ]:
employees = pd.DataFrame({
 'employee_id':[1,2,3,4,5],
 'name':['john', 'Anna', 'Peter', 'Linda', 'Bob'],
 'department':['HR', 'IT', 'Finanace', 'IT', 'HR']})
salary = pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[60000,80000,65000,70000,90000],
    'bonus':[5000,10000,5000,10000,5000]
})

In [ ]:
employees

   employee_id   name department
0            1   john         HR
1            2   Anna         IT
2            3  Peter   Finanace
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salary

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   5000
3            6   70000  10000
4            7   90000   5000

In [ ]:
# merge the common rows
# on must be common

# how refer to the type of merging means inner mergin means only the common part are show while the outer means all common non common parts are shown
# inner means like AND and outer is OR

In [ ]:
pd.merge(employees,salary, on = 'employee_id',how= 'outer')

   employee_id   name department   salary    bonus
0            1   john         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter   Finanace  65000.0   5000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0  10000.0
6            7    NaN        NaN  90000.0   5000.0

In [ ]:
pd.merge(employees,salary, on = 'employee_id',how= 'left')
# how = 'left'means that the left table  rows are show but the value are according to the common or how = 'right'

   employee_id   name department   salary    bonus
0            1   john         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter   Finanace  65000.0   5000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salary, on = 'employee_id',how= 'inner')

   employee_id   name department  salary  bonus
0            1   john         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter   Finanace   65000   5000

In [ ]:
#  concatination

In [ ]:
pd.concat([employees , salary])
# on the basis of rows

   employee_id   name department   salary    bonus
0            1   john         HR      NaN      NaN
1            2   Anna         IT      NaN      NaN
2            3  Peter   Finanace      NaN      NaN
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
0            1    NaN        NaN  60000.0   5000.0
1            2    NaN        NaN  80000.0  10000.0
2            3    NaN        NaN  65000.0   5000.0
3            6    NaN        NaN  70000.0  10000.0
4            7    NaN        NaN  90000.0   5000.0

In [ ]:
pd.concat([employees , salary],axis= 1)
# on the basis of rows

   employee_id   name department  employee_id  salary  bonus
0            1   john         HR            1   60000   5000
1            2   Anna         IT            2   80000  10000
2            3  Peter   Finanace            3   65000   5000
3            4  Linda         IT            6   70000  10000
4            5    Bob         HR            7   90000   5000

In [ ]:
#  joining 2 data frame

In [ ]:
df1 = pd.DataFrame({
    'name':['john', 'Anna', 'Peter', 'Linda', 'Bob'],

}, index=[1,2,3,4,5])
df2= pd.DataFrame({
    'score': [ 85,90,75,80,95]
}, index=[3,4,5,6,7])

In [ ]:
df1

    name
1   john
2   Anna
3  Peter
4  Linda
5    Bob

In [ ]:
df2

   score
3     85
4     90
5     75
6     80
7     95

In [ ]:
df1.join(df2 , how = 'outer')

    name  score
1   john    NaN
2   Anna    NaN
3  Peter   85.0
4  Linda   90.0
5    Bob   75.0
6    NaN   80.0
7    NaN   95.0

In [ ]:
df2.join(df1)

   score   name
3     85  Peter
4     90  Linda
5     75    Bob
6     80    NaN
7     95    NaN

In [ ]:
# revise using chatgpt

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7])

In [ ]:
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
data_list = {
    "name":["aman", "ritu", "kunal", "gaurav"],
    "age":[10,20,30,40],
    "marks":[100,200,300,400]
}

In [ ]:
pd.DataFrame(data_list,index = ['a', 'b', 'c', 'd'])

     name  age  marks
a    aman   10    100
b    ritu   20    200
c   kunal   30    300
d  gaurav   40    400

In [ ]:
df = pd.read_csv("/phishing_training_data.csv")

In [ ]:
df

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
0,0,0,2,1,1,1,1,0,2,2,1216,1,81,1
1,3,0,0,0,1,1,4,0,2,0,1566,8,75,1
2,1,1,2,1,6,6,0,0,2,0,965,5,53,1
3,0,0,0,0,6,1,0,0,0,0,194,6,35,0
4,1,0,0,0,1,1,0,0,0,0,570,0,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,3,1,1,1,5,1,1,1,0,0,415,6,75,1
9996,1,0,0,0,0,0,0,0,0,0,431,1,7,0
9997,0,0,0,0,0,0,1,0,0,0,109,1,15,0
9998,1,1,2,1,6,2,0,1,0,0,1680,7,97,1
9999,1,0,0,0,0,1,1,0,0,0,702,0,16,0

In [ ]:
df.head(5)

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
0,0,0,2,1,1,1,1,0,2,2,1216,1,81,1
1,3,0,0,0,1,1,4,0,2,0,1566,8,75,1
2,1,1,2,1,6,6,0,0,2,0,965,5,53,1
3,0,0,0,0,6,1,0,0,0,0,194,6,35,0
4,1,0,0,0,1,1,0,0,0,0,570,0,12,0

In [ ]:
df.tail(10)

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
9990,0,0,0,2,0,1,2,0,0,2,1274,5,89,1
9991,0,0,1,0,1,2,3,1,0,2,1276,4,89,1
9992,4,1,1,2,5,2,2,1,1,2,1310,0,89,1
9993,0,0,0,0,1,1,1,0,0,0,425,0,27,0
9994,1,0,0,0,1,1,0,0,0,0,407,1,15,0
9995,3,1,1,1,5,1,1,1,0,0,415,6,75,1
9996,1,0,0,0,0,0,0,0,0,0,431,1,7,0
9997,0,0,0,0,0,0,1,0,0,0,109,1,15,0
9998,1,1,2,1,6,2,0,1,0,0,1680,7,97,1
9999,1,0,0,0,0,1,1,0,0,0,702,0,16,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url_count                    10000 non-null  int64
 1   ip_url_count                 10000 non-null  int64
 2   suspicious_tld_count         10000 non-null  int64
 3   long_url_count               10000 non-null  int64
 4   urgent_count                 10000 non-null  int64
 5   credential_count             10000 non-null  int64
 6   threat_count                 10000 non-null  int64
 7   reply_to_mismatch            10000 non-null  int64
 8   attachment_count             10000 non-null  int64
 9   suspicious_attachment_count  10000 non-null  int64
 10  text_length                  10000 non-null  int64
 11  exclamation_count            10000 non-null  int64
 12  phishing_percentage          10000 non-null  int64
 13  label                        10000 non-null  int64
dtypes: int64(14)
memory usage: 1.1 MB

In [ ]:
df.describe()

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
count,10000.00000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.00000,10000.000000
mean,1.50230,0.345700,0.58550,0.642800,2.257500,1.976400,1.496900,0.270800,0.496800,0.345500,668.2919,2.923600,49.13270,0.493700
std,1.52139,0.652406,0.79357,0.808501,2.047929,1.991442,1.611412,0.444395,0.762658,0.674667,416.0067,2.705937,29.10434,0.499985
min,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.0000,0.000000,0.00000,0.000000
25%,0.00000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,335.0000,1.000000,24.00000,0.000000
50%,1.00000,0.000000,0.00000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,575.0000,2.000000,49.00000,0.000000
75%,2.00000,0.000000,1.00000,1.000000,4.000000,4.000000,3.000000,1.000000,1.000000,0.000000,924.0000,5.000000,74.00000,1.000000
max,6.00000,2.000000,2.00000,2.000000,6.000000,6.000000,5.000000,1.000000,2.000000,2.000000,1965.0000,8.000000,100.00000,1.000000

In [ ]:
df.shape

(10000, 14)

In [ ]:
df["url_count"]

0       0
1       3
2       1
3       0
4       1
       ..
9995    3
9996    1
9997    0
9998    1
9999    1
Name: url_count, Length: 10000, dtype: int64

In [ ]:
df.iloc[0:3]

,url_count,ip_url_count,suspicious_tld_count,long_url_count,urgent_count,credential_count,threat_count,reply_to_mismatch,attachment_count,suspicious_attachment_count,text_length,exclamation_count,phishing_percentage,label
0,0,0,2,1,1,1,1,0,2,2,1216,1,81,1
1,3,0,0,0,1,1,4,0,2,0,1566,8,75,1
2,1,1,2,1,6,6,0,0,2,0,965,5,53,1

In [ ]:
df.loc[df["url_count"]>10]

Empty DataFrame
Columns: [url_count, ip_url_count, suspicious_tld_count, long_url_count, urgent_count, credential_count, threat_count, reply_to_mismatch, attachment_count, suspicious_attachment_count, text_length, exclamation_count, phishing_percentage, label]
Index: []